default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: check-case-conflict # checks for files that would conflict in case-insensitive file systems
      - id: check-docstring-first # checks a common error of defining a docstring after code
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang
      - id: check-shebang-scripts-are-executable # ensures that (non-binary) files with a shebang are executable
      - id: check-merge-conflict # checks for files that contain merge conflict strings
      - id: check-symlinks # checks for symlinks which do not point to anything
      - id: check-toml # checks toml files for parseable syntax
      - id: check-yaml # checks yaml files for parseable syntax
        args: [--unsafe]
      - id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source
      - id: detect-private-key # detects the presence of private keys
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline
      - id: mixed-line-ending # replaces or checks mixed line ending
      - id: name-tests-test # verifies that test files are named correctly
      - id: trailing-whitespace # trims trailing whitespace

  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types: [yaml]

  # word spelling linter
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args:
          - --skip=libs/**,logs/**,*.bib,*.ipynb,*.js,**/vqa_eval_metric.py
          - --ignore-words-list=ans,nd,ned,nin,hart,rouge,vist

  # md formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter
          - mdformat-toc
          - mdformat-black
